version: '3.8'  # Or latest version

services:
  mysql:
    image: mysql:8.0
    restart: always # Ensures container restarts on failure or system reboot
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: vaccine_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306" # Maps container port 3306 to host port 3306.  Change the host port if needed, but keep the container port 3306.
    volumes:
      - mysql_data:/var/lib/mysql # Persists data across container restarts
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backup:
    image: mysql:8.0
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backups:/backups
    command: |
      /bin/bash -c '
      while true; do
        timestamp=$$(date +%Y%m%d_%H%M%S)
        mysqldump -h mysql -u root -psecret vaccine_db > /backups/backup_$$timestamp.sql
        find /backups -name "backup_*.sql" -type f -mtime +7 -delete
        sleep 3600
      done
      '
    restart: always

volumes:
  mysql_data: # Named volume for MySQL data