version: '3.8'  # Or latest version

services:
  mysql:
    image: mysql:latest  # Or a specific version like mysql:8.0
    restart: always # Ensures container restarts on failure or system reboot
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: vaccine_db
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3307:3306" # Maps container port 3306 to host port 3306.  Change the host port if needed, but keep the container port 3306.
    volumes:
      - mysql_data:/var/lib/mysql # Persists data across container restarts
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "appuser", "-papppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s


volumes:
  mysql_data: # Named volume for MySQL data